{% set python_min = '3.10' %}
{% set name = "uniserde" %}
{% set version = "0.3.14" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/uniserde-{{ version }}.tar.gz
  sha256: f0bd3289afab3661e88746b8e7bce43f925d29a4e1cd5c6c1fd972d0d6958024

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - python >={{ python_min }}
    - python-dateutil >=2.8.2
    - typing-extensions >=4.7.1

test:
  imports:
    - uniserde
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://gitlab.com/mad-moo/uniserde
  summary: Convention based, effortless serialization and deserialization
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - thewchan
