{% set python_min = "3.10" %}
{% set name = "uniserde" %}
{% set version = "0.3.15" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/uniserde-{{ version }}.tar.gz
  sha256: d1cf8e72359f9f9150a33bf105e497cebc98bd428b21e1e06356a5e72f7b5fb6

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling ==1.26.3
    - hatch-vcs
    - pip
  run:
    - python >={{ python_min }}
    - python-dateutil >=2.8.2
    - typing-extensions >=4.7.1

test:
  imports:
    - uniserde
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://gitlab.com/mad-moo/uniserde
  summary: Convention based, effortless serialization and deserialization
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - thewchan
